name: Check PR

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install deps
        run: npm ci
      - name: Build and check types
        run: npm run build
      - name: Check types
        run: npm run tsc